'''file_1 = open("new.text","r")
#name=file_1.read()
name=file_1.readlines()
file_1.close()
print(name)
#name_list=name.split("\n")
file_1 = open("new.text","w")
#name=file_1.read()
name=file_1.write("hello")
file_1.close()
print(name)
#name_list=name.split("\n")'''
file_1=open("new.text","r+")
name=file_1.read()
file_1.write("hello")
file_1.close()